### ISSUE TITLE
Contrast for Visual Search task

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#20]
The contrast for the **Visual Search** task have not been defined [here](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_public/utils_contrasts.py), therefore neither in the csv file.

**Comment by bthirion** [comment]
It is: https://github.com/hbp-brain-charting/public_analysis_code/blob/003a0df00238949f8b1529dfde568edc7d96e6bd/ibc_public/utils_contrasts.py#L550

**Comment by ferponcem** [comment]
The thing is we have only initiated the function for `Search` there, but I can't see the definitions for contrasts, and I am looking for a combination of conditions to generate the `probe_item_four–probe_item_two` contrast, because from what I got from the documentation is that this depends on whether *memory_array_two* or *memory_array_four* happened before *probe_item_absent* and *probe_item_present*. 

One suggestion @man-shu did is to rename the *probe_item_absent* and *probe_item_present* events to something like **probe_item_absent_memory_two** and **probe_item_absent_memory_four** to know which condition came before and that way we could just sum or subtract those events to form the contrast.

This is specific for the `probe_item_four–probe_item_two` contrast, the rest of them I think I completed, you can tell me if they're accurate.

**Comment by bthirion** [comment]
Hm, we need to dedicate a bit of time to this. Tentatively: next Tuesday at 5pm, together with @man-shu

**Comment by ferponcem** [comment]
Okay, here are some details of the things I've changed:

* I modified the [event files](https://github.com/hbp-brain-charting/analysis_pipeline/tree/master/ibc_main/neurospin_data/info) for each subject that has performed it (9 subs in total), to add the `probe_item_??_present` events, depending on the previous array shown.
* I updated the `utils_contrast.py` script on the [search definition](https://github.com/hbp-brain-charting/public_analysis_code/blob/f1ef7667dbe28fc1a6e2a356ab33a8256b31abf0/ibc_public/utils_contrasts.py#L550) to add those new events and define all contrasts. @bthirion here is where I would specifically ask for you to check that it is correct. 
* Updated the [csv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/VisualSearch.csv) where we define the contrast.
* Updated the [ibc_conditions.tsv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L330) to describe these new events.
* Updated the [documentation](https://github.com/hbp-brain-charting/admin/blob/dbe93918e2841245c3da0c8c782947239d3b0766/documentation/documentation.tex#L5742) with these changes as well.

Did I miss something? What do you think of this changes?

**Comment by bthirion** [comment]
* In the csv file, there is some renaming to perform, e.g. 'probe_item–trial_onset' -> 'probe_item' (several occurrences)
* Also, 'delay_vis–delay_wm' spec does not sound right n the csv file.
* it seems that you in describe only 7 contrasts in teh doc, while you actually specified more ?

Also, note that I may hit bugs when I run the code... will let you know.

**Comment by ferponcem** [comment]
Thanks for spotting those two things on the [csv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/VisualSearch.csv), I corrected them.

Regarding the contrast specification on the documentation, we actually have only 7 contrasts, but in the code I was checking the blocks around this tasks and for most of them you define all the conditions and the contrasts in those lines, so I tried to be consistent and I listed both conditions and contrasts. Hopefully we can make it better when we see the errors we get.

**Comment by bthirion** [comment]
OK.

**Comment by ferponcem** [comment]
@bthirion I'm curious to know as if the analysis with the modified event files went okay

**Comment by bthirion** [comment]
Yes, it worked, thx.
