### ISSUE TITLE
Contrasts for the TwobyTwo task

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#21]
As we discussed, I modified the conditions of the TwoByTwo task and therefore, the [contrasts file](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/TwoByTwo.csv). The changes were:

* Duplicating the number of contrast and adding `cue_` and `stim_` as prefix to the conditions to match the [contrast script](https://github.com/hbp-brain-charting/public_analysis_code/blob/9df11f8e3665541c2c1b6086af42a3c6e573ff7a/ibc_public/utils_contrasts.py#L1301). 
* Adding them as regressors and the the `1` columns.
* Modifying the names from `cue_task_switch_cue_switch`  to`cue_taskswitch_cueswitch` to match the code and the [event files](https://github.com/hbp-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/stanford/ses-01/sub-04_task-TwobyTwo_run1_events.tsv).

@bthirion I am wondering whether it's necessary to copy this same structure in the [documentation file](https://github.com/hbp-brain-charting/admin/blob/e43ee1c9451a52ded945517fbf1ff3e92363ebef/documentation/documentation.tex#L4392), I mean duplicating the number of conditions and specifying each one as a regressor, I think they're better off like this, but let me know what you think. (I have to put each contrast below the conditions because now they are all in a single table for all Stanford tasks, but you get the point).

**Comment by bthirion** [comment]
No, we need to be consistent, otherwise people won't be able to figure out what is what.

**Comment by bthirion** [comment]
I'm not sure I undertsand the description well. Saying that the cue is  "Color'' should be equivalent to saying ``Orange/Blue' ? Similarly, ``Magnitude'' = ``High/Low'' ? Actually, I don't understand the distinction that is made here.

**Comment by ferponcem** [comment]
As I understood, we're adapting this tasks from the battery they're mentioning in [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5801197/). For this particular task (two-by-two) they were looking for **Stimulus and Task Switch Cost**. Then for this they point out to [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3074508/), where they explain task-switching and cue switching, and they propose this model of cue-encoding for tasks where task-switching procedures may be confounded with cue-switching. So in the overall the aim is to model task switching and cue switching and being able to see them independently and the extent to which they confound.

So at the end, for this protocol, on each trial you see a number on screen and you have to perform one of two possible tasks: 1) judging if a number is greater or less than 5 or 2) judging if the number shown is orange or blue. For each task, we have two different cues that point to the same action: for 1) you could read either string `Magnitude` or `Low/High` as cues before the digit appears, both strings mean you should judge whether x<5. For 2) you could read either `Orange/Blue` or `Color` as cues, both meaning you need to say which color the digit is.

I hope you got a better sense of the task now! I also updated the description of the task in the [documentation](https://github.com/hbp-brain-charting/admin/blob/721bc3371cf903f6b30814a7a24b6917e2a38549/documentation/documentation.tex#L4392) and in the [task csv](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_tasks.tsv#L42), hoping is better.

**Comment by ferponcem** [comment]
As you can see in the [battery's paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5801197/) originally they were working on a `three-by-two` task (3 possible tasks with 2 different cues each) and they have a [simulator](https://expfactory.github.io/v1/threebytwo.html) for it. However, the paper just says that after some test for viability they decided to change to a `two-by-two` task, which is the one we implemented.. My point is, they only have the simulator for the three-by-two, so I am not sure about including it in the documentation.

**Comment by bthirion** [comment]
> As you can see in the [battery's paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5801197/) originally they were working on a `three-by-two` task (3 possible tasks with 2 different cues each) and they have a [simulator](https://expfactory.github.io/v1/threebytwo.html) for it. However, the paper just says that after some test for viability they decided to change to a `two-by-two` task, which is the one we implemented.. My point is, they only have the simulator for the three-by-two, so I am not sure about including it in the documentation.

We can include it, but giving the explanation you just gave. This an only help.

**Comment by bthirion** [comment]
> 

Based on the clarifications you made (thx !), can you check the condition/contrast description we have ?

**Comment by ferponcem** [comment]
> > 
> 
> Based on the clarifications you made (thx !), can you check the condition/contrast description we have ?

Yes! Right now we're modeling the appearance of both the stimuli and the cues as conditions, when either, both or none changes (cue or task), see [conditions_csv](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L194). Hopefully the descriptions are clear enough.

For the contrast we're using every condition as regressor, plus two more contrasts: `task_switch-stay` to combine the effect of task switching; and `cue_switch-stay. See [script](https://github.com/hbp-brain-charting/public_analysis_code/blob/9df11f8e3665541c2c1b6086af42a3c6e573ff7a/ibc_public/utils_contrasts.py#L1301) and [csv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/TwoByTwo.csv).

**Comment by ferponcem** [comment]
> > As you can see in the [battery's paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5801197/) originally they were working on a `three-by-two` task (3 possible tasks with 2 different cues each) and they have a [simulator](https://expfactory.github.io/v1/threebytwo.html) for it. However, the paper just says that after some test for viability they decided to change to a `two-by-two` task, which is the one we implemented.. My point is, they only have the simulator for the three-by-two, so I am not sure about including it in the documentation.
> 
> We can include it, but giving the explanation you just gave. This an only help.

Cool! I will also include it for the other available tasks.

**Comment by ferponcem** [comment]
@bthirion for this issue, the only thing left to do is approve the contents of the [conditions file](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L194) and the format on the [contrast sheet](https://github.com/individual-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/TwoByTwo.csv), hopefully it will be enough!
