### ISSUE TITLE
Abstraction task

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#22]
I've realized that this protocol is not incorporated on the [contrasts script](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_public/utils_contrasts.py) yet.

So I've added a short description to the task descriptions [file](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_tasks.tsv#L76).

I did the same for the conditions and for the contrasts, but here is where I think we could use some discussion:
For the [conditions](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L385), I have listed all possible combinations that occur on the [event files](https://github.com/hbp-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/abstraction/task-abstraction_sub-04_run-01_events.tsv), except for the button presses for now.
* I included both for localizer and main task all together, is it okay or should we treat them as separated tasks?
* Shall we model them all like this? I was thinking maybe there's no need to distinguish between every example for each category, like instead of doing `animals_bird_edge`, `animals_giraffe_edge`, `animals_butterfly_edge` and so on, we could model the whole category: `animals_edge`, what do you think?
* Shall we model the star on screen and the subject's response??

For the [contrasts](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/Abstraction.csv), I just took the broader categories: `animals_edge`, because there are too many already! But if is not the best, I can expand it to all the conditions (`animals_giraffe_edge`, `animals_butterfly_edge`, etc).

Depending on what we decide I will update the documentation **tex file**.
@bthirion @man-shu  what do you think?

**Comment by bthirion** [comment]
Thx.
* I've updated the conditions file to simplify descriptions.
* Regarding the events files, please replace the 'y' with something meaningful.
* I'm not sure that the localizer and main task should be handled together: we need to discuss that.
* `animals_bird_edge` vs `animals_edge`:  I think that `animals_bird_edge`  is OK for now.
* star on screen: No,
* response: yes
* contrasts: OK

**Comment by ferponcem** [comment]
Thanks! 
* I've added a simple condition (and it's regressor) for `response`.
* Modified the event files, see [an example](https://github.com/hbp-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/abstraction/task-abstraction_sub-04_run-01_events.tsv) to have `response` insteado of `y`.
**Please note** that sub-06 and sub-11 have 4 runs instead of 8, I am guessing those were the sessions acquired before the decision to split into 8 runs. Let me know if there's something that needs to be done here.
* For now I am keeping localizer and main task together, we can discuss in our next meeting.
* For the contrasts, I opened a pull request #26 so that we can add those to the script. See [here](https://github.com/hbp-brain-charting/public_analysis_code/pull/26)

**Comment by ferponcem** [comment]
status update: 
* Split the session in [Abstraction](https://github.com/individual-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/Abstraction.csv) and [AbstractionLocalizer](https://github.com/individual-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/AbstractionLocalizer.csv). See changes also in [ibc_conditions](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L389).
* Added duration to `response` events, [example](https://github.com/individual-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/abstraction/task-abstraction_sub-04_run-01_events.tsv)

I will close this issue once we run the analysis!
