### ISSUE TITLE
MDTB - Emotion files

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#23]
For this two tasks, I would like to know what you think @bthirion @man-shu 

**For MDTB**
* [Here](https://github.com/hbp-brain-charting/admin/blob/1522a2441165e7be2e0e1284522938de9c430e00/documentation/documentation.tex#L6550) we have the general information and each task description.
* [Here](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_tasks.tsv#L77) I copied most of the information but I shortened a bit, what do you think? Is it okay like this or should I copy it exactly the same, all in 1 cell?
* [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L465) updated with conditions and descriptions.
* [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/MDTB.csv) with contrasts in matrix form, I am not sure if it's okay that I include the first 13 columns since they're regressors for each of the conditions, or if I should delete them and just keep the last 6, where we actually perform some operations.

**For Emotion**
* [Here](https://github.com/hbp-brain-charting/admin/blob/1522a2441165e7be2e0e1284522938de9c430e00/documentation/documentation.tex#L6809) we have the general information description.
* [Here](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_tasks.tsv#L78) I copied the description
* [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L478) updated with conditions and descriptions.
* [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/Emotion.csv) with contrasts in matrix form, same question as in MDTB.

**Comment by bthirion** [comment]
> ****
> 
>     * [Here](https://github.com/hbp-brain-charting/admin/blob/1522a2441165e7be2e0e1284522938de9c430e00/documentation/documentation.tex#L6550) we have the general information and each task description.

Thx ! I'd like to dit it a little bit. Is this in a pull request ? That would make it easier.

**Comment by bthirion** [comment]
> [Here](https://github.com/hbp-brain-charting/admin/blob/1522a2441165e7be2e0e1284522938de9c430e00/documentation/documentation.tex#L6809) we have the general information description.

LGTM

**Comment by bthirion** [comment]
> * [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L465) updated with conditions and descriptions.
> 
> * [File](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/MDTB.csv) with contrasts in matrix form, I am not sure if it's okay that I include the first 13 columns since they're regressors for each of the conditions, or if I should delete them and just keep the last 6, where we actually perform some operations.

LGTM

**Comment by ferponcem** [comment]
> Thx ! I'd like to dit it a little bit. Is this in a pull request ? That would make it easier.

It's already on the documentation file on the admin master branch, however we decided to start making all the changes on the [csv file](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_tasks.tsv#L78), also regarding comment 2. It would be great if you could give us your feedback for the descriptions there!

**Comment by ferponcem** [comment]
I am closing this issue as the majority of things look good! We will need to go over the tasks and conditions' descriptions in the future more carefully to make them more understandable, for now I think we reached the goal (:
