### ISSUE TITLE
Aomic Working Memory sub-task

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#27]
While checking I realized Aomic consists of 5 sub-tasks and we have all the event files (see [example](https://github.com/hbp-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/aomic/task-piopworkingmemory_sub-04_run-01_events.tsv)) but we're only modeling 4 in the script. The missing one is *working memory*.

So I added the conditions to the [file](https://github.com/hbp-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv#L385) and added a new contrast [sheet](https://github.com/hbp-brain-charting/public_analysis_code/blob/feature/contrasts_descriptions/ibc_data/contrasts/WorkingMemoryAomic.csv) because we're modeling each AOMIC task separately. 

If those contrasts look good, I can go ahead and create a PR to add them to the code, let me know what you think @bthirion !

**Comment by bthirion** [comment]
LGTM, thx !
