### ISSUE TITLE
Typo in StroopAomic

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#29]
While adding the contrasts for **StroopAomic** to [all_contrasts](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/all_contrasts.tsv), I found a typo in some contrasts' names: `congurent` instead of `congruent`, see [line](https://github.com/individual-brain-charting/public_analysis_code/blob/d2e03cc2c233a6d8eb24a68e11592154f4033834/ibc_public/utils_contrasts.py#L475). @bthirion I wonder if I can change it without breaking other codes, because then whenever we use the info in all_contrasts, they're not going to match, and we need those to be nice since we're displaying the info on the documentation.

**Comment by bthirion** [comment]
I think that the typo is not there in utils_contrasts.py ? If it isn't, then you should obviously fix it in all_contrasts.tsv. Thx !

**Comment by ferponcem** [comment]
Actually it's the other way around, I am adding this task to *all_contrasts.tsv* just now, so I am copying the names from *utils_contrasts.py* to make sure the contrasts' names match, that's how I realized there's a typo in lines 475, 476, 497 and 498, see [here](https://github.com/individual-brain-charting/public_analysis_code/blob/d2e03cc2c233a6d8eb24a68e11592154f4033834/ibc_public/utils_contrasts.py#L475). It's tricky because for example line 475 says in con**gur**ent - con**gru**ent, so the first, positive one is the typo and the negative is okay.

**Comment by ferponcem** [comment]
The issue was sorted! Now the only small remaining is a `congurent-incongruent.png` file, but I assume it's harmless since the correct files with proper names are there and the code has the correct string. :tada:
