### ISSUE TITLE
Contrast in RewProc

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#30]
There's this contrast named `stim` on the *RewardProcessing* task, and I am not sure of its meaning. We didn't have it in the list of contrasts in the original take of the [documentation](https://individual-brain-charting.github.io/docs/tasks.html#rewproc) but it is there on the contrast script, see [line](https://github.com/individual-brain-charting/public_analysis_code/blob/54385dd3d43ca05b832beb9b43f0a68456f2145e/ibc_public/utils_contrasts.py#L1011). 
By looking at the event files (see [example](https://github.com/individual-brain-charting/analysis_pipeline/blob/master/ibc_main/neurospin_data/info/sub-04/reward_proc/task-reward-proc_sub-04_run-01_events.tsv)) it looks like it refers to the stimulus' onset, ie when the two images appear on screen and the next event is the subjects response and then fixation.
@bthirion do you think we should keep this? And if so, how do we define it?

**Comment by bthirion** [comment]
I think that  this is simply a cue. 
Best,

**Comment by ferponcem** [comment]
Nice, I will tag it as such!
