### ISSUE TITLE
Naming issue with FingerTap (FBIRN)

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#34]
In [all_contrasts](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/all_contrasts.tsv#L562) the finger tapping tasks is called *FingerTapping*, which I think it's a mistake, because in the files the name is `res_task-FingerTap_space...` ; and same in [utils_contrast](https://github.com/individual-brain-charting/public_analysis_code/blob/f9176721d8e9a611f396c1cf2494bd6939cacb6f/ibc_public/utils_contrasts.py#L891).
@bthirion So if there's no other place where this could be a problem, I could directly correct this in the all_contrasts.csv file.

**Comment by bthirion** [comment]
+1 for consistency, so lets' move to FingerTap for the moment... but we'll probably move later all occurrences to FingerTapping later,as FingerTap is obviously not a good name.

**Comment by ferponcem** [comment]
The thing is that we already have a FingerTapping:
FingerTapping -> CamCAN
FingerTap -> FBIRN

**Comment by bthirion** [comment]
OK, makes sense. Then let's go for FingerTap  :-(
