### ISSUE TITLE
Double conditions.csv file

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#37]
Currently in [ibc_data](https://github.com/individual-brain-charting/public_analysis_code/tree/master/ibc_data) we have two conditions csv files:

* [ibc_conditions](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/ibc_conditions.tsv), which is used in the web documentation. It contains all conditions per task with a description.
* [conditions](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/conditions.tsv), which is used in [ibc_public script](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_public/utils_data.py#L35) and probably others. It contains only a list of conditions per task.

I would like to open a PR and change the **ibc_public script** to use `ibc_conditions` file instead, given that it's more complete. I will also have a look on where else is this file is being updated, so that we don't duplicate files or break things. @bthirion @man-shu

**Comment by bthirion** [comment]
Have you worked on it alread ? If not, I'm going to do it.

**Comment by ferponcem** [comment]
I am actually opening a PR just now, I can try to finish it and you can check it.

**Comment by bthirion** [comment]
All right

**Comment by ferponcem** [comment]
Sorted with PR #45, now we only have one file to maintain :tada:
