### ISSUE TITLE
Contrast disguised in NARPS

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#40]
In the documentation for the NARPS task, the list of conditions show `reject-accept`, and after, the list of contrast in the next table also shows `reject-accept`.

My intuition is that this is just duplicated, so I can go ahead and delete that condition and keep it only as a contrast. @man-shu

**Comment by bthirion** [comment]
We should rather have  reject/accept conditions.

**Comment by ferponcem** [comment]
Reject and accept exist as conditions but accompanied by `weakly` or `strongly`, which results in 4 conditions:
* strongly_accept
* weakly_accept
* weakly_reject
* strongly_reject

See [narps conditions](https://individual-brain-charting.github.io/docs/tasks.html#narps). 

In the meantime, I will remove this `reject-accept` from the conditions list.

**Comment by bthirion** [comment]
Then we're good I think.
