### ISSUE TITLE
Conditions that lack statistical map

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#41]
This issue appeared when creating figures for data paper 5, maybe it's only relevant for this context but I would like to hear your thoughts.

We have a script that averages the contrast maps across subjects for each conditions to perform a *condition similarity analysis*. Ideally, we would have every condition's map for the analysis, but the sometimes the condition itself was not included on the [utils_contrast script](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_public/utils_contrasts.py#L792), so no map was created.

So far what I did was to manually add some of the contrast names that could be easily matched to conditions or that are a generalized  version of the conditions and for which the maps exist, so that they could be included on the analysis.

Here there's a detailed list of this, not all are critical, just to list them all:

* **VisualSearch**: I added `probe_item`, which is defined as the combination of probe_item_two_present, probe_item_four_present, probe_item_two_absent and probe_item_four_absent, in utils_contrasts

* **ItemRecognition**: I added `encode`, which is defined as the sum of encode1, encode3 and encode5. In fact this is the only condition that is being analyzed for this task, since the rest of the maps are operations that don't really relate to the effect of the condition itself. Example: conditions are probe1_mem and probe5_mem, but the available map is probe5_mem-probe1_mem, which I can't really relate to any of the conditions easily.

* **RewProc**: conditions green, purple, left and right don't have a map, but I didn't add anything as there's nothing that I could easily relate (the closest existing map could be green-purple, for example, but that's not exactly equivalent to any of those) and there are other conditions taken into account.

* **FingerTap**: there's no map for the conditions fingertap or rest. I added fingertap-rest, in the hope that it could relate to fingertap as it's the condition of interest.

* **Checkerboard**:  there's no map for the conditions checkerboard or fixation. I added checkerboard-fixation, in the hope that it could relate to the checkerboard condition as it's the interesting one.

* **SpatialNavigation**: there's no map for the encoding_phase condition, it was commented out from utils_contrast. Maybe deliberately? 

* **NARPS**: there's no map for the stim condition, maybe deliberately?

@bthirion @man-shu

**Comment by bthirion** [comment]
Note sure I understand: Fore Visual search, the conditions are `probe_item_two_present`, `probe_item_four_present`, `probe_item_two_absent` and `probe_item_four_absent`. `probe_item` is not a condition, but a combination of conditions (hence, a contrast)
Similarly, in ItemRecognition, `encode` is not a condition.
I'll try and have a deeper look in the coming days.

**Comment by ferponcem** [comment]
Yes, those are contrasts that sum up conditions, but for instance, in the case of **RewProc**, it's the only way I could add this task to the analysis, otherwise, there are not maps for it; and my thinking is that that map contains information of the 4 conditions so it would be informative of the `encode` situation. 
The same for `probe_item` for **VisualSearch**, but for this tasks is not that necesary because there are maps for other conditions.

**Comment by bthirion** [comment]
For RewProc, purple, green, left and right aren't proper conditions, but already combinations thereof so we should not include them.

**Comment by bthirion** [comment]
I'm adding the missing contrasts for FingerTap and Checkerboard.

**Comment by ferponcem** [comment]
I get the point, but in the case of **ItemRecognition**, there are no contrast maps for any of the conditions, so no maps that could be used in the analysis. See here in the [list](https://individual-brain-charting.github.io/docs/tasks.html#itemrecognition) of ItemReco conditions and contrasts.
So that's why I added the `encode` maps, which are a sum of the `encode1`, `encode3` and `encode5` against fixation. Maybe we should instead define more contrasts and run their analysis, because I don't think we want to exclude the task from the analysis. @bthirion

**Comment by bthirion** [comment]
OK I'll look at that tomorrow. IMHO, we should rather add the elementary conditions: encode1, encode3 and encode5
Thx,

**Comment by bthirion** [comment]
All right, i'm adding them now.

**Comment by ferponcem** [comment]
I am assuming you will first add them to `utils_contrast.py` and then run the analysis? Or maybe I can add them to the script myself?

**Comment by ferponcem** [comment]
I see they exist in Nsp server :tada:
So maybe you already added them to the `utils_contrast.py` and just need to push

**Comment by bthirion** [comment]
Yes, most likely.

**Comment by ferponcem** [comment]
I see all the updates in utils_contrast and all the maps in drago too :tada:
Thanks!!!
