### ISSUE TITLE
Condition that exist just for one subject

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#42]
This issue appeared when creating figures for data paper 5, maybe it's only relevant for this context but I would like to hear your thoughts. @bthirion @man-shu 

We have a script that averages the contrast maps across subjects for each conditions to perform a condition similarity analysis. So ideally we would have conditions' statistical maps that we could average across all subjects. However, for the **Scene** task, the `scene_possible_incorrect` condition map only exists for 3 subjects, instead of the 9 subjects who performed the tasks. 

I am not sure if the average of 3 subjects for this condition is comparable to the average of 9 subjects for the rest of  conditions, so I took it out of the analysis, but maybe we should keep it? 

And I am not sure why this condition is only being created for two, specifically `sub-09`, `sub-11` and `sub-14`. I am trying to have a deeper look.

**Comment by bthirion** [comment]
This is a problem with this design.  I recommend to ignore that condition pour data paper 5.

**Comment by ferponcem** [comment]
Okay, then we'll do so!
