### ISSUE TITLE
Display of intermediate contrasts

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#43]
For VisualSearch, we have defined in [utils_contrast](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_public/utils_contrasts.py#L792) the following *intermediate* contrasts:
* `probe_item_absent`: as a sum of the other contrasts probe_item_two_absent + probe_item_four_absent
* `probe_item_present`: as a sum of the other contrasts probe_item_two_present + probe_item_four_present
* `probe_item_four`: as a sum of the other contrasts probe_item_four_present + probe_item_four_absent
* `probe_item_two`: as a sum of the other contrasts probe_item_two_present + probe_item_two_absent
* `search_array_four`: as a sum of the other contrasts search_array_four_absent + search_array_four_present
* `search_array_two`: as a sum of the other contrasts search_array_two_absent + search_array_two_present

Should these also be displayed on the documentation on the contrast list? @bthirion @man-shu

**Comment by bthirion** [comment]
All these should be part of the estimated contrasts (the code indicates they are; I'll rerun it).

**Comment by ferponcem** [comment]
Apologies for the confusion, all the contrasts on this list have maps (nii and gii) already!
I just meant that they are not displayed on the documentation on the list of contrasts for VisualSearch, and maybe they should be there.

**Comment by bthirion** [comment]
Indeed. Can you take care of that ?

**Comment by ferponcem** [comment]
Done! Check [docs](https://individual-brain-charting.github.io/docs/tasks.html#visualsearch) for a full list of contrasts. :tada:
