### ISSUE TITLE
WMAomic or WorkingMemoryAomic

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#48]
The derivatives in the cluster have this name format: `~/ibc/derivatives/sub-04/ses-44/res_task-WMAomic_space-MNI305_dir-ffx/`
However, on the documentation we have it as [WorkingMemoryAomic](https://individual-brain-charting.github.io/docs/tasks.html#workingmemoryaomic). I'm wondering, of course it's easier to modify the documentation to have them matching but I wanted to make sure there's no other place where I would need to check. 
In utils_contrasts the paradigm_id is as [WMAomic](https://github.com/individual-brain-charting/public_analysis_code/blob/ce18a4c69c692408ea9c39237f423aab9cab89b7/ibc_public/utils_contrasts.py#L153C11-L153C11) .
@bthirion

**Comment by bthirion** [comment]
Thx for raising that.
We have to call it WMAomic everywhere, since this is the name we used everywhere to name files.
