### ISSUE TITLE
AOMIC battery surface files

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#49]
The **Aomic** battery surface derivatives are missing for in both clusters, only those in MNI space are there. Maybe the analysis has not been launched?
Specifically, tasks HarririAomic, FacesAomic, StroopAomic and WMAomic, all in the same session.
@bthirion

**Comment by bthirion** [comment]
Thx for reporting. Launching it now.

**Comment by bthirion** [comment]
Should be OK now. Please confirm

**Comment by ferponcem** [comment]
Yes! They are there in Nsp but not in drago yet. I guess I will check in a few hours

**Comment by ferponcem** [comment]
Coming back to this, I see them in Nsp cluster but not in drago.
In `drago` they are only available for sub-04.
Maybe we need to restart the transfer? @bthirion

**Comment by bthirion** [comment]
Can you check if this is OK now ? Best

**Comment by ferponcem** [comment]
They are there just for `sub-04` and `sub-06`, for the rest of subjects is still pending I guess?

**Comment by bthirion** [comment]
OK, I'm relaunching the sync, that was not complete indeed. Thx.

**Comment by ferponcem** [comment]
We're getting there! The copy is almost completed, just missing for `sub-14` and `sub-15`.

**Comment by bthirion** [comment]
Yes, it's ongoing.

**Comment by bthirion** [comment]
Should be good now, closing. Please reopen ifneed be.
