### ISSUE TITLE
OptimismBias contrasts

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#51]
Opening after our discussion about **OptimismBias** contrasts @bthirion 
This is a **naming issue**, the contrast names are not in the same format as those of the rest of tasks, examples:
`future_positive_vs_negative`, `past_positive_vs_negative`, etc (see [full list](https://individual-brain-charting.github.io/docs/tasks.html#optimismbias), see [utils_contrasts](https://github.com/individual-brain-charting/public_analysis_code/blob/2588cab68381b3e9da07b9f44d3bb5328f409824/ibc_public/utils_contrasts.py#L682)).

Maybe we could consider renaming the contrast and relaunch the analysis, or maybe it's just worth noting :eyes:

**Comment by bthirion** [comment]
Lets' close that one for the moment.
