### ISSUE TITLE
Wedge or WedgeAnti, WedgeClock

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#52]
In the documentation, we have `Wedge` as the name of the task, but in the files, it can be either `WedgeAnti` or `WedgeClock`. 
As discussed, the documentation must match the filenames, so I will:

* Separate them in the documentation and set a description for each one.
* Differentiate which conditions and contrasts are for each one
* Make the distinction in main_contrasts.

**Comment by bthirion** [comment]
Indeed, thx !

**Comment by ferponcem** [comment]
See result in the [documentation](https://individual-brain-charting.github.io/docs/tasks.html#wedgeclock) !
