### ISSUE TITLE
Echelle_valence to scale_valence

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#53]
For the **Emotion** task, one of the contrasts is `echelle_valence`, see [utils_contrast](https://github.com/individual-brain-charting/public_analysis_code/blob/05fa5ed9a28f6e623b0a64684f664ae57a5fd215/ibc_public/utils_contrasts.py#L285)
This is intended for the section on the task where participants rate their state after all the negative images.
Maybe this should be `valence_scale` or simply `scale`.

**Comment by bthirion** [comment]
+1 for `valence scale`, but we need to change utils_contrasts and rerun the corresponding glms.

**Comment by bthirion** [comment]
This has been  implemented. Can you update the all_contrsats.tsv and main_contsarts.tsv file ?

**Comment by ferponcem** [comment]
Great, see [changes](https://github.com/individual-brain-charting/public_analysis_code/commit/1b5e293491565c104fe49cfa6d082845313c5cf1).
Thanks!
