### ISSUE TITLE
Contrasts ids for Mario

### ISSUE THREAD

**Issue by bthirion** [individual-brain-charting/public_analysis_code#57]
We have changed the contrasts ids in mario @ferponcem can you update the all_contrasts and main_contrasts files accordingly ?

**Comment by ferponcem** [comment]
Updated in [all_contrasts](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/all_contrasts.tsv#L785) and [main_contrasts](https://github.com/individual-brain-charting/public_analysis_code/blob/master/ibc_data/main_contrasts.tsv#L405) ! 🎉
