### ISSUE TITLE
Abstraction missing runs

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#62]
@bthirion In drago, for all subjects, there are missing derivatives for the last 4 runs of **Abstraction**:
`derivatives/sub-04/ses-45/func/` contains the 8 runs up to the `dc` prefix step, but after that we only see the first 4 runs (for the files with the `rdc` and `wrdc` prefix). 
This is the case for all subjects that did the Abstraction task: sub-04, sub-06, sub-08, sub-09, sub-11, sub-12, sub-14, sub-15

**Comment by ferponcem** [comment]
I don't think this is the cause but some of the **source data** is also missing:
`sourcedata/sub-06/ses-45/func` just has the first 4 runs
`sourcedata/sub-11/ses-47/func/` just has the first 4 runs

**Comment by bthirion** [comment]
This one should be good now ! Please LMK.

**Comment by ferponcem** [comment]
Almost ! There are just two subjects that are still incomplete: **sub-06** and **sub-11**
Coincidently, the source data for the 4 last runs for those two subs is also missing from drago.
`sourcedata/sub-06/ses-45/func` and `derivatives/sub-06/ses-45/func`
`sourcedata/sub-11/ses-47/func` and `derivatives/sub-11/ses-47/func`

**Comment by bthirion** [comment]
IIRC for these 2 subjects, we only have 4 runs, but they are twice longer and represent the double aquisition time wrt other participants. Can you confirm ?

**Comment by ferponcem** [comment]
Oh that's right... thanks for the clarification. Is this something worth adding to the documentation?

**Comment by bthirion** [comment]
Indeed, that would be very useful to add a note in the docs.

**Comment by ferponcem** [comment]
Little note added to the docs ! Thanks 💯
