### ISSUE TITLE
data_parser doesn't browse through all the files

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#67]
In `ibc_public/utils_data` we have the function **data_parser** that creates a db with the available files for the requested tasks.
I've come across two issues when working with this:

Mainly, when looking for the fixed effects maps, [this line](https://github.com/individual-brain-charting/public_analysis_code/blob/5d717c770512f46a9c9c86301b80ebc19ecd4ac8/ibc_public/utils_data.py#L322) only allows the script to look for files matching the last entry on the acquisitions list, so it's unable to find all derivatives.

And second, when looking for a specific acquisition type (for instances "pa"), it fails because [here](https://github.com/individual-brain-charting/public_analysis_code/blob/5d717c770512f46a9c9c86301b80ebc19ecd4ac8/ibc_public/utils_data.py#L323) we create a dir- flag as part of a [wildcard](https://github.com/individual-brain-charting/public_analysis_code/blob/5d717c770512f46a9c9c86301b80ebc19ecd4ac8/ibc_public/utils_data.py#L338) that doesn't match the actual file path:
wildcard: `derivatives/sub-04/.../res_task-Color_space-MNI152_dir-pa/`
actual path: `derivatives/sub-04/.../res_task-Color_space-MNI152_run-01_dir-pa/`

I can open a PR about this, I just would like to hear @bthirion thoughts on this.

**Comment by bthirion** [comment]
I don't understand the first issue

For the second issue, it's easy to solve, PR welcome.

**Comment by ferponcem** [comment]
For the first issue, I hope I am not mistaken but:

The function receives the desired acquisition type [here](https://github.com/individual-brain-charting/public_analysis_code/blob/5d717c770512f46a9c9c86301b80ebc19ecd4ac8/ibc_public/utils_data.py#L105), with **`all**` as default.
But later **acquisition** is rewritten [here](https://github.com/individual-brain-charting/public_analysis_code/blob/5d717c770512f46a9c9c86301b80ebc19ecd4ac8/ibc_public/utils_data.py#L268) during the preprocessed files parsing.

So after, when the code passes to the derivatives, it doesn't search for **'all'** or the specified acquisition type, instead it just looks for whatever the value of acquisition was at the end.

To reproduce:
```python
from ibc_public.utils_data import data_parser, DERIVATIVES
PTS = ['sub-04', 'sub-06', 'sub-08']
task_list = ["Visu"]

db = data_parser(
    derivatives=DERIVATIVES, subject_list=PTS, task_list=task_lis
)
```
Output: only `pa` dir derivative files (contrast maps) on the db, since `pa` was the last value of the acquisition variable.

This is also a quick fix, just changing the name of the parameter. Let me know what you think and I will open a PR 😸

**Comment by bthirion** [comment]
I think you're right. Please submit a PR.
