### ISSUE TITLE
Missing smooth_derivatives for OptimismBias

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#70]
For subjects **sub-12** and **sub-15**, there are no smooth_derivatives for the *OptimismBias* task in drago.
The corresponding sessions would be `/smooth_derivatives/sub-12/ses-44` and `/smooth_derivatives/sub-15/ses-43`. 

The rest of subjects and the derivatives are fine!

**Comment by bthirion** [comment]
Should be OK now. Do you mind checking ?

**Comment by ferponcem** [comment]
It is, thanks ! 🚀
