### ISSUE TITLE
LePetitPrince Localizer as a separate task

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#71]
Just opening up the discussion about the localizer for the LPP task:
In the [documentation](https://individual-brain-charting.github.io/docs/tasks.html#lepetitprince) we just mention the localizer as part of the task, but it was actually acquired on a different session.
- Should we provide a separated description for the localizer and treat it as a separate task, as we do for [LocalizerAbstraction](https://individual-brain-charting.github.io/docs/tasks.html#localizerabstraction)
- If so, I'm not convinced by the naming in the files, it's just tagged as Localizer. Would it be possible to name it something like *LocalizerLPP* ?

See example: 
```
$ls /derivatives/sub-04/ses-27
res_task-LePetitPrince_space-fsaverage7_dir-ffx
.
.

$ ls /derivatives/sub-04/ses-28
res_task-Localizer_space-fsaverage7_dir-ffx
.
.
```
@bthirion what do you think?

**Comment by bthirion** [comment]
* The session number should not matter. It is part of the file name for BIDS reasons, but that's a detail.
* But I think that you're right, it turns out to be a standalone task.
* I agree to rename, but this will take a bit of time

**Comment by bthirion** [comment]
I think it should be fine now. please LMK.

**Comment by ferponcem** [comment]
In drago I think it worked for `sub-04`, `sub-05` and `sub-06` so far.
For the rest of subjects, I still don't see the changes, maybe I can check a little later?

**Comment by bthirion** [comment]
From what I see the other subjects are fine too in sourcedata.
What data directory  are you referring to ?

**Comment by ferponcem** [comment]
I was looking at the derivatives directory

**Comment by bthirion** [comment]
Should be good now ?

**Comment by ferponcem** [comment]
Yes, all good! 🎉
