### ISSUE TITLE
Typos in tags

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/public_analysis_code#74]
There's a semi-invisible typo in a tag given to a contrast for the self task, see: https://github.com/individual-brain-charting/public_analysis_code/blob/00d13ce4e94bc17de602409b0e41606d38dab79c/ibc_data/all_contrasts.tsv#L201
The typo is a `\t` char.
It must have escaped me at some point, but since it wasn't me who annotated this task, I wanted to keep track of it.
This is most likely two tags: memory and reading.
@bthirion should I correct it right away, or should I include it as another revision in #73 ?

**Comment by bthirion** [comment]
Correct it right away, thx.

**Comment by ferponcem** [comment]
Corrected in https://github.com/individual-brain-charting/public_analysis_code/commit/ca6bd24950e366361f2365cfb37c40ff51f94346
Thanks! 🚀
