### ISSUE TITLE
[BUG] make_db returns empty dataset in the volumetric case.

### ISSUE THREAD

**Issue by pbarbarant** [individual-brain-charting/public_analysis_code#79]
Hi!

When passing `space="MNI305"` to `make_db` (which is done automatically in `make_vol_db` for example). The fetcher returns an empty dataframe. On the other hand, all surf options (`space="fsaverage*"`) seem to work ok.

**Comment by ferponcem** [comment]
Hi, it seems like `make_db` function might not be updated for the volumetric maps, thanks for the catch!
For the moment, could you try the `data_parser` function for volumetric maps?
And I can update `make_db` later today !

**Comment by pbarbarant** [comment]
Hi @ferponcem , it seems that switching from `MNI305` to `MNI152` solves the issue. Is it specific to our internal storage? If no I can draft a quick PR.
Best,

**Comment by ferponcem** [comment]
Yes, that's all the issue !
A PR adding `MNI152` to the volumetric space would be great !
