### ISSUE TITLE
Running surface_based_analysis.py on data from OpenNeuro

### ISSUE THREAD

**Issue by ngohgia** [individual-brain-charting/public_analysis_code#8]
Dear profs. I'm trying to run the surface_based_anlaysis.py on the data downloaded from https://openneuro.org/datasets/ds002685/versions/1.3.0
May I know how I should set the hardcoded paths in surface_based_analysis.py with respect to the downloaded data? In particular, for these paths
```
work_dir = '/neurospin/ibc/derivatives'
mem = Memory(base_dir='/neurospin/tmp/ibc')

os.environ['SUBJECTS_DIR'] = ''"
```

Thank you very much!

**Comment by bthirion** [comment]
Hi. 
These are just some write directory where you put some temporary (mem) or main (work_dir) results. Any directory where you have enough place to host data are good for that purpose.
Best,
